### ISSUE TITLE
Update issue in dataverse

### ISSUE THREAD

**Issue by wheintz** [r-geoflow/geoflow#210]
Hi Emmanuel,

We found a new issue this dataverse at https://data.indores.fr :

```
`"Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: 1a63409456f9`
```
Publication of dataset is going well. When updating, the first line of gsheet is working, but then the workflow stops with the following error : 

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: 1a63409456f9
```
If you have any idea ...

Cheers,

 Wilfried

**Comment by eblondel** [comment]
@wheintz can we discuss that lively?

**Comment by wheintz** [comment]
Hi @eblondel, we don't know in fact... The only thing I can tell you is that we never had this issue with inrae dataverse. But today we still have the error.

Thanks

**Comment by eblondel** [comment]
Seems to be an issue with with service provider
