### ISSUE TITLE
Improve zenodo action to add multi authors not limiting to owners

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#252]
There is a need to overcome the limitation in Zenodo action, and need to discuss about this. As for now, the pivot metadata model maps to the Zenodo action, from owner to authors. This is too restrictive, and not necessarily correct. Ownership is one thing, Authorship is another. 
`author` is a role that is quite used, even in ISO 19115; so in principle this could be used as primary role targeting the Zenodo action. This would mean that at least one author should be made available. In case no author is set, then we can put the available 'owner'.

cc @juldebar @wheintz @abennici

**Comment by kikislater** [comment]
Any news on this ?

**Comment by eblondel** [comment]
@kikislater I admit I had not browsed back on this :-) I had put it for recordatory. I suppose this is a task I take over as part of IRD sponsoring if @juldebar is ok with that.

**Comment by eblondel** [comment]
some code pushed here @kikislater for you to test
