### ISSUE TITLE
Refactor geoflow action fun handling

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#262]
Relates to #261 
This is the current status regarding the way actions can be interfaced:

* global actions (embedded or custom - provided by user) have to be defined with a  named`function` interface like:

```R
my_fun <- function(entity, config, options){}
```
where `my_fun` should be the action id.

* local actions: for which no function has to be provided

This is highly criticizable and not really convenient for the user, for multiple reasons detailed below:

* Not the same logic is applied for global vs. local actions. Proposal: handle a function for all actions
* For global actions, giving a function name is useless, in particular for custom actions where we constrain the user to name the function with the `id` defined for the action. 
* The `options` are not clear, especially for testing local actions, these are the action options. This 'argument' should be removed from the function interface. The `action` definition should be made available. From there, options will be easily grab using `action$options`, or using util to develop in #261 which will then avoid re-writing action options default values in the action function, but inherit them from the action definition;
* This will open the door to test implementation of #125

Hence, any action (global embedded, global custom, local) will have to be designed within a function interface as follows:

```R
function(action, entity, config){

   opts <- action$options
   ....
}
```

In addition, for global embedded actions, an attempt will be made to create a separate folder 'actions' under the 'inst' folder

@abennici @juldebar @wheintz if you have any questions, feel free. I will anyway assist you in changes where needed

**Comment by BastienIRD** [comment]
Are the global custom actions not concerned by this update ? As it still mandatory to have an "options" argument in the function ? (Line 517 of geoflow::initWorkflow https://github.com/eblondel/geoflow/blob/master/R/initWorkflow.R)

**Comment by eblondel** [comment]
All actions should be concerned by this code refactoring/harmonization
