### ISSUE TITLE
Evaluate how to support 'license' in ISO 19115 action

### ISSUE THREAD

**Issue by EmilieLerigoleur** [r-geoflow/geoflow#269]
Hello,
when I put in Rights gsheet column:

license:licence ouverte CC BY 2.0 FR_
otherConstraint:Utilisation libre sous réserve de mentionner la source (a minima le nom du producteur) et la date de sa dernière mise à jour

The license does not appear in the Geonetwork catalogue and it is not mentioned in the XML metadata file.
Only otherConstraint seems to be well managed.

see: https://geo.driihm.fr/geonetwork/ohmi-tes/fre/catalog.search#/metadata/7d71b52b-a58a-422c-80ca-d8f34157dee6 (but it frequently changes- because of tests !)

Thanks for your help,
Emilie

**Comment by EmilieLerigoleur** [comment]
ok I understand, thanks!

**Comment by eblondel** [comment]
@EmilieLerigoleur i've pushed some tentative solution here which consists in scanning the `license` specified as `Rights`. If any we add the use constraint / restriction `license` (which is an ISO codelist "restriction" term); and we add the license(s) as `use limitation`
