### ISSUE TITLE
Polygon extent issue

### ISSUE THREAD

**Issue by wheintz** [r-geoflow/geoflow#281]
Hi Emmanuel,

We found a new issue in geoflow with polygon extent. If the WKT is not rectangular (in gsheet), polygon extent appears empty in geonetwork and a SRID error occurs.

Thanks in advance,

 Wilfried

**Comment by eblondel** [comment]
@wheintz can you share the web link of a geonetwork metadata having this issue?

**Comment by eblondel** [comment]
@wheintz can you share an example?
