### ISSUE TITLE
problem with temporel coverage column in metadata table

### ISSUE THREAD

**Issue by juliepierson** [r-geoflow/geoflow#288]
Hi,
When I set a date like this in temporalCoverage of metadata table : "2022-06-23" or "2022-06-13T02:00:00Z", I get an error message when running initWorkflow : `Erreur dans as.POSIXlt.character(x, tz, ...) : la chaîne de caractères n'est pas dans un format standard non ambigu`
When I set it like this : "2022-06-23/2022-06-23" there's no error message.
Strangely, the problem seems to appear only for the first line of CSV, there's no problem with dates like "2022-06-23" or "2022-06-13T02:00:00Z" for the other lines in CSV.
I tried with and without quotes, and I tried editing the CSV in a text file editor to make sure there was no hidden formatting.
Thanks for your help :smiley:

**Comment by eblondel** [comment]
Can you send me the CSV file by email?

**Comment by juliepierson** [comment]
Done, thanks!

**Comment by eblondel** [comment]
Hi @juliepierson sorry for the delay.. Can you tell me the version of readr you have installed?
Also please run this code (with your csv file):

```R
data = as.data.frame( readr::read_csv("metadata_table_maraisbreton_v2.csv") )
data$TemporalCoverage
class(data$TemporalCoverage)
```

and tell me the the result

**Comment by juliepierson** [comment]
Thanks for your answer. I have version 2.1.3 of readr. Here are the results :

`> data = as.data.frame( readr::read_csv("metadata_table_maraisbreton_v2.csv") )`
`Rows: 4 Columns: 15                                                                                                                                           
── Column specification ───────────────────────────────────────────────────────────────────────────────────────────────────
Delimiter: ","
chr  (13): Identifier, Title, Description, Subject, Creator, Date, Type, Language, Relation, Rights, Provenance, Data, ...
lgl   (1): SpatialCoverage
dttm  (1): TemporalCoverage`

`> data$TemporalCoverage`
`[1] "2022-06-13 02:00:00 UTC" "2022-06-13 02:00:00 UTC" "2022-06-13 02:00:00 UTC" "2022-06-13 02:00:00 UTC"`

`> class(data$TemporalCoverage)`
`[1] "POSIXct" "POSIXt" `

**Comment by eblondel** [comment]
@juliepierson after investigation it appears to be related to upgrade of readr/vroom packages. I've pushed a tentative fix.

**Comment by juliepierson** [comment]
Yes, it works ! Thanks !!

**Comment by eblondel** [comment]
Cool!
