### ISSUE TITLE
working directory changes when using geoflow

### ISSUE THREAD

**Issue by juliepierson** [r-geoflow/geoflow#291]
Working directory in R gets changed to directory of current job when executing geoflow.

**Comment by eblondel** [comment]
@juliepierson i've pushed something, can you re-install and re-try using metadata files with relative paths to your working directory? thanks in advance

**Comment by eblondel** [comment]
@juliepierson Wait! there is still something wrong

**Comment by eblondel** [comment]
@juliepierson can you test?

**Comment by eblondel** [comment]
cool :-)
