### ISSUE TITLE
Support 'dir' data multiple source accessor with remote accessors

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#304]
The 'dir' approach was implemented with support of multilayer and the capacity to have an entity `geoflow_data` object with other `geoflow_data` objects as children. The implementation was done for local dir access. The logic is completely different in case of remote data access.

Not all data accessors will be provided with this capacity. At now this will be implemented for `ocs` software / data accessors.

@mrouan @juliepierson

**Comment by eblondel** [comment]
@mrouan @juliepierson I've pushed a first implementation to support data `dir` in combination with a different data accessor through data `access` property. This provides the general framework (including support of a new `list` method feature for the definition of data accessors) + the implementation for OCS.

To use it it's quite straighforward. You declare the `access:ocs` in your Data column, and set the remote dir path for the `dir` property.
Example:

```
access:ocs_
dir:MyDrive/geoflow/testdir
```

Looking forward to your feedback,

**Comment by juliepierson** [comment]
Thanks @eblondel, it looks great ! Looking forward to test this, but maybe not until january 2023
