### ISSUE TITLE
Add overwrite options to geoserver publishing action 

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#329]
Deactivating the `geosapi` action in a workflow has side effects in other actions (eg ISO 19115 where OGC service links will be not be added). On the other hand, a user does not necessarily want to re-run the full geoserver action. We can distinguish various use cases:
- the user doesn't want to redo the upload and layer configuration
- the user doesn't want to redo the upload, but would like to update the layer configuration
- the user does want to redo the upload, but would not like to update the layer configuration

From this, a set of 3 options could be added to the `geosapi` action:
- `overwrite` (default is TRUE): to indicate if the actual action business logic should be run.
- `overwrite_upload` (default is TRUE): to indicate if the data upload should be (re)run. If `overwrite` is FALSE, this one will be set to FALSE (prevealing over it)
- `overwrite_layer` (default is TRUE): to indicate if the layer configuration should be (re)run. If `overwrite` is FALSE, this one will be set to FALSE (prevealing over it)

cc @juldebar @kikislater

**Comment by kikislater** [comment]
Thanks, worth trying

**Comment by kikislater** [comment]
When 
	    "overwrite_upload": true
and 
	    "overwrite_layer": false

abstract in geoserver is not updated, is this actual behaviour ?

**Comment by kikislater** [comment]
When
`"overwrite_upload": false`
and
`"overwrite_layer": true`

abstract in geoserver is not updated, is this actual behaviour ?

**Comment by eblondel** [comment]
If `overwrite_upload` is false, you assume you uploaded a dataset through the Geoserver API (eg. a GeoPackage) and you don't want to re-upload it because it didn't change. 
If `overwrite_layer` is true, the layer will be republished (without any physical data download behind). So we will update layer title for example (based on the entity metadata).
