### ISSUE TITLE
Error when loading csv from github in a Rstudio server 4.3 (typo fix to be made)

### ISSUE THREAD

**Issue by bastienird** [r-geoflow/geoflow#338]
With latest geoflow version (0.20230720)

When running no local nor global action in entities and informing csv to be loaded from github, the following error occurs:

Error in FUN(X[[i]], ...) : object 'NULLdatasource_parts' not found
Error in withVisible(...elt(i)) : 

I cannot recreate this bug on my machine running on R 4.2.
The bug seems to be related to the line 600 in geoflow_entity R6Class where there is a typo. ("NULLdatasource_parts[1]" which should be "datasource_parts[1]")

**Comment by kikislater** [comment]
Thanks
Come from this commit: https://github.com/r-geoflow/geoflow/commit/75d81bef55a2188874319334d7d8351bb43521b1#diff-77d87065a56cb594e9acbc04bfd7833947759c28766f40a5798c7fdb37350838
