### ISSUE TITLE
Bug in entity$asDataFrame() 

### ISSUE THREAD

**Issue by bastienird** [r-geoflow/geoflow#341]
On R 4.3.1 bug when running entity$asDataFrame() with an entity having two temporal_extent.

Error returned when running line 1741:
_}else if(length(names(self$temporal_extent))==2 && names(self$temporal_extent) %in% c("start","end")){_

The second part return a vector (ex c(TRUE, TRUE)) that is not considered as a logical.

Fixed in line 1741: (adding all() function to handle the logical)
_}else if(length(names(self$temporal_extent))==2 && **all(names(self$temporal_extent) %in% c("start","end")))**{_ 

see https://github.com/bastienird/geoflow/commit/1f19b3bda4d0689720b87b88a97c11e273b135f8

**Comment by eblondel** [comment]
Can you send a PR?

**Comment by eblondel** [comment]
Thanks @bastienird feel free to report any other bug, in particular on `èntity$asDataFrame()`
