### ISSUE TITLE
[zen4r_deposit_record] Setting license in rights return error

### ISSUE THREAD

**Issue by kikislater** [r-geoflow/geoflow#351]
From Rights column in entities I have this : 

> useLimitation:Utilisation libre sous réserve de mentionner la source (a minima le nom du producteur) et la date de sa dernière mise à jour_
> accessConstraint:otherRestrictions_
> license:GPL-3.0_
> useConstraint:intellectualPropertyRights

`license` code is set from here : https://sandbox.zenodo.org/api/licenses/?q=&size=1000 where "id":"GPL-3.0" exists

Running workflow return me this error => 

```
Error in if (license %in% accepted_licenses) { : 
  l'argument est de longueur nulle
Erreur dans withVisible(...elt(i)) : 
  Workflow failed during execution, check logs
```

I added some log like `config$logger.info(sprintf("licenses: '%s'", licenses))` with this value in logs:
```
[geoflow][zenodo][INFO] licenses: '<environment>'  and licenses[[1]]$value is NULL
```

**Comment by eblondel** [comment]
Thanks for reporting. Relates to #298 and consolidation of model for for geoflow `rights`, in particular https://github.com/r-geoflow/geoflow/commit/63b2ddf95a93dab3e47961c351070daa5030a4e0 that was propagated to ISO 19115 (essentially tested in #298) but not in other metadata actions.

**Comment by eblondel** [comment]
@kikislater please reclose the issue if it works ok now

**Comment by kikislater** [comment]
Thanks, it works now ! Tested with GPL-3.0 and GPL-2.0
@juldebar
