### ISSUE TITLE
Implement Zenodo `grants` in geoflow

### ISSUE THREAD

**Issue by kikislater** [r-geoflow/geoflow#354]
Not available at this moment, it needs to be done to fill and change grants

**Comment by eblondel** [comment]
Ok, I can develop a mapping with entity relations and a new `key`.

**Comment by eblondel** [comment]
Fixed with https://github.com/r-geoflow/geoflow/commit/b834e5639f1206f40e7e1df841f75c18d74171ed

**Comment by kikislater** [comment]
Thanks
