### ISSUE TITLE
Support Zenodo ` Additional notes` in geoflow

### ISSUE THREAD

**Issue by kikislater** [r-geoflow/geoflow#355]
Additional notes could be a nice feature to add : 

Quoting Zenodo website : 
```
Optional. OpenAIRE-supported projects only. For other funding acknowledgements, please use the Additional Notes field.
Note: a human Zenodo curator will need to validate your upload - you may experience a delay before it is available in OpenAIR
```

**Comment by eblondel** [comment]
fixed typo at https://github.com/r-geoflow/geoflow/commit/ef053241cbc725ff33d1d6e20674d1d0be93abd0 tested with integration test, operational

**Comment by kikislater** [comment]
It works ! thank you
![image](https://github.com/r-geoflow/geoflow/assets/13238064/36c8c73e-9b02-4bdc-b2f2-2e6825b3700c)
