### ISSUE TITLE
problem of negative values of variable not taken into account when calculating intervals

### ISSUE THREAD

**Issue by helraynal** [r-geoflow/geoflow#377]
it seems that the calculation of classes to use for the map and for a given variable (whatever the method: ckmeans methods, intervals ) doesn't take into account the negative values of the variable

**Comment by eblondel** [comment]
@helraynal i close this issue here and pasted it at https://github.com/eblondel/OpenFairViewer/issues/172 as this an issue with OpenFairViewer. In your case I had a look and the variable _thresholding_ is deactivated so it's likely to be a bug. I will try to analyze it ASAP.
