### ISSUE TITLE
Support DBI scanning through entity handler options instead of specific handlers

### ISSUE THREAD

**Issue by eblondel** [r-geoflow/geoflow#386]
With the support of handler options (see #346), there is no need to use specific designed handlers like the one developed in #347 for DBI scanning: 
* Handlers `dbi_csv`, `dbi_gsheet`, `dbi_excel` will be deprecated (with addition of `active`/`deprecated` `status` and associates `notes` to characterize handlers). 
* Handlers `csv`, `gsheet`, `excel` will be enriched with an option `enrich_from_dbi` that will support the same DBI scanning logic.

In addition the `ocs` handler will have the same `enrich_from_dbi` option. This will enable to use CSV/Excel entities stored in OCS with DB scanning.

**Comment by eblondel** [comment]
This error let think geoflow has not been reinstalled correctly, as this shows old code
Try to restart R and reinstall geoflow.

**Comment by wheintz** [comment]
Thank you @eblondel ,
Indeed I had to restart my R session... Now everything is OK!
Cheers.
